# Generated by Django 3.2 on 2021-05-01 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarmas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarma',
            name='idAlarma',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
