# Generated by Django 3.2 on 2021-05-01 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarmas', '0002_alter_alarma_idalarma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarma',
            name='idAlarma',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
